.

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -174,7 +174,15 @@ stages:
 
     - script: |
         json=$(curl -s --location "${TEST_API_GATEWAY_URL}/rest/apigateway/archive?fixingMissingVersions=false&overwrite=*" --header 'accept: application/json' -u ${TEST_API_GATEWAY_USERNAME}:${TEST_API_GATEWAY_PASSWORD} --form "zipFile=@./resources/apim/ContactManagementAPI.zip")
-        echo "Response: $json"
+        all_success=$(echo $json | jq 'all(.ArchiveResult[].[]; .status == "Success")')
+
+        if [[ $all_success == "true" ]]; then
+          echo "Import successful"
+        else
+          echo "Import failed"
+          echo "Response: $json"
+          exit 1
+        fi
       displayName: 'Deploy the API proxy'
       env:
         TEST_API_GATEWAY_PASSWORD: $(TEST_API_GATEWAY_PASSWORD)
